Configuración Workflow

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -237,6 +237,18 @@ jobs:
           IMAGE_REF: ${{ env.IMAGE_REF }}
         # Aplica le kubernetes a la imagen localmente
 
+      - name: Check rollout status and logs if fail
+        run: |
+          echo "⏳ Waiting for deployment rollout..."
+          if ! kubectl rollout status deployment/vitalapp-backend --timeout=300s; then
+          echo "🚨 Deployment failed. Showing pod logs:"
+          kubectl get pods -l app=vitalapp-backend
+          POD_NAME=$(kubectl get pods -l app=vitalapp-backend -o jsonpath="{.items[0].metadata.name}")
+          echo "Logs from pod: $POD_NAME"
+          kubectl logs $POD_NAME
+            exit 1
+          fi
+
       - name: Health Check (verify pod)
         run: |
           kubectl get pods
